---
- name: Logging into Fluentd Docker Registry
  docker_login:
    registry: "{{ flurentd_registry }}"
    username: "{{ flurentd_registry_username }}"
    password: "{{ flurentd_registry_password }}"
  when: flurentd_registry_login == true

- name: Pulling Fluentd image
  docker_image:
     name: "{{ flurentd_registry }}{{ flurentd_image_name }}"
     state: present

#- name: Logging into Kibana Docker Registry
#  docker_login:
#    registry: "{{ kibana_registry }}"
#    username: "{{ kibana_registry_username }}"
#    password: "{{ kibana_registry_password }}"
#  when: kibana_registry_login == true
#
#- name: Pulling Kibana image
#  docker_image:
#     name: "{{ kibana_registry }}{{ kibana_image_name }}"
#     state: present
#
#- name: Logging into Elasticsearch Docker Registry
#  docker_login:
#    registry: "{{ elasticsearch_registry }}"
#    username: "{{ elasticsearch_registry_username }}"
#    password: "{{ elasticsearch_registry_password }}"
#  when: elasticsearch_registry_login == true
#
#- name: Pulling Elasticsearch image
#  docker_image:
#     name: "{{ elasticsearch_registry }}{{ elasticsearch_image_name }}"
#     state: present

